# 日志配置
logging:
  level:
    root: info
    org.springframework.web: INFO

# ===== 美团SaaS配置 ===== #
# 诺诺开票平台配置
meituan:
  api:
    # appId
    appId: ${MEITUAN_APP_ID:8580}
    # appSecret
    appSecret: ${MEITUAN_APP_SECRET:a273343145dc44394c3a1365f49c6c22}

# ===== 天财SaaS配置 ===== #
tiancai:
  api:
    # appId
    appId: ${TIANCAI_APP_ID:2a36bf799e6b4c90941bf84b67789111}
    # accessId
    accessId: ${TIANCAI_APP_ACCESS_ID:a1fca758ed104119889f46df3528d9fa}
