# 日志配置
logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG

# ===== 美团SaaS配置 ===== #
# 诺诺开票平台配置
meituan:
  api:
    # appId
    appId: ${MEITUAN_APP_ID:8580}
    # appSecret
    appSecret: ${MEITUAN_APP_SECRET:a273343145dc44394c3a1365f49c6c22}

# ===== 天财SaaS配置 ===== #
tiancai:
  # http还是https
  protocol: ${PROTOCOL:https}
  # o2oa 服务地址
  url: ${URL:cysms.wuuxiang.com}
  # o2oa 服务端口
  port: ${PORT:443}
  api:
    # appId
    appId: ${TIANCAI_APP_ID:2a36bf799e6b4c90941bf84b67789111}
    # accessId
    accessId: ${TIANCAI_APP_ACCESS_ID:a1fca758ed104119889f46df3528d9fa}
    # centerId 餐饮集团ID
    centerId: ${TIANCAI_APP_CENTER_ID:94630}

# 调度平台配置
xxl:
  job:
    executor:
      appName: ${XXL_JOB_EXECUTOR_APPNAME:genesis-meituan-openapi-java-service}
      logPath: /data/applogs/xxl-job/jobhandler
      ip: ${XXL_JOB_EXECUTOR_IP:10.0.4.13}
      port: ${XXL_JOB_EXECUTOR_PORT:2345}
      accessToken: ${XXL_JOB_EXECUTOR_ACCESS_TOKEN:dasj2nd81jf9asjdkl5jk234}
      intentionalities: 3
    admin:
      # 调度中心部署地址
      addresses: ${XXL_JOB_ADMIN_ADDRESSES:http://10.0.4.13:2222/xxl-job-admin}
