spring:
  main:
    allow-circular-references: true
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: genesis-meituan-openapi-java-service
  # 设置上传文件大小.
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: true
    open-in-view: false
  datasource:
    # 数据源配置 本地开发环境
    #    url: ${DATASOURCE_URL:jdbc:mysql://150.158.93.174:3306/}dth_gyl?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8&connectTimeout=30000&socketTimeout=30000&useSSL=false&useCursorFetch=true&rewriteBatchedStatements=true
    #    username: ${DATASOURCE_USER_NAME:root}
    #    password: ${DATASOURCE_PASSWORD:Mc666888@@}
    # 数据源配置 大叹号正式库mysql
    url: ${DATASOURCE_URL:jdbc:mysql://62.234.13.121:3306/}dth_data?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8&connectTimeout=30000&socketTimeout=30000&useSSL=false&useCursorFetch=true&rewriteBatchedStatements=true
    username: ${DATASOURCE_USER_NAME:root}
    password: ${DATASOURCE_PASSWORD:Dth666888@@}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      idle-timeout: 100000
      max-lifetime: 110000
      connection-test-query: SELECT 1

server:
  port: 8080


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: 对接美团SaaS平台服务
  try-host: http://localhost:${server.port}


# ===== 美团SaaS配置 ===== #
meituan:
  api:
    # appId
    appId: ${MEITUAN_APP_ID:8580}
    # appSecret
    appSecret: ${MEITUAN_APP_SECRET:a273343145dc44394c3a1365f49c6c22}
    # 单店单次最大评论数
    maxCommentCount: ${MEITUAN_MAX_COMMENT_COUNT:1000}


# ===== 天财SaaS配置 ===== #
tiancai:
  # http还是https
  protocol: ${PROTOCOL:https}
  # o2oa 服务地址
  url: ${URL:cysms.wuuxiang.com}
  # 自有服务器 url（目前只有成本卡在用）
  url2: ${URL2:http://dthzb.sm5.fxscm.net}
  # o2oa 服务端口
  port: ${PORT:443}
  api:
    # appId
    appId: ${TIANCAI_APP_ID:2a36bf799e6b4c90941bf84b67789111}
    # accessId
    accessId: ${TIANCAI_APP_ACCESS_ID:a1fca758ed104119889f46df3528d9fa}
    # centerId 餐饮集团ID
    centerId: ${TIANCAI_APP_CENTER_ID:94630}
    # 自有服务器账号（目前只有成本卡在用）
    username: ${TIANCAI_APP_USERNAME:admin}
    # 自有服务器密码
    password: ${TIANCAI_APP_PASSWORD:123456}


# 调度平台配置
xxl:
  job:
    executor:
      appName: ${XXL_JOB_EXECUTOR_APPNAME:genesis-meituan-openapi-java-service}
      logPath: /data/applogs/xxl-job/jobhandler
      accessToken: ${XXL_JOB_EXECUTOR_ACCESS_TOKEN:dasj2nd81jf9asjdkl5jk234}
      intentionalities: 3
    admin:
      # 调度中心部署地址
      addresses: ${XXL_JOB_ADMIN_ADDRESSES:http://xxl-job-admin:8080/xxl-job-admin}
